version: '3.4'
networks:
  mysql:
    external: true
services:
  dm:
    image: golang:1.14
    volumes:
      - ../dm/cmd/sync/etc/dm.json:/cds/dm.json
      - ./build/dm:/cds/dm
    command:
       /cds/dm -f /cds/dm.json
  galaxy:
    image: golang:1.14
    ports:
      - "8080:8080"
    volumes:
      - ../galaxy/etc/galaxy-api.json:/cds/galaxy-api.json
      - ./build/galaxy:/cds/galaxy1
    command:
      /cds/galaxy1 -f /cds/galaxy-api.json
  rtu:
    image: golang:1.14
    volumes:
      - ../../cds:/cds
    command:
      /cds/docker/build/rtu -f /cds/rtu/conf.json
  nginx:
    image: nginx
    ports:
      - 3414:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../logs:/var/log/nginx
      - ./html:/usr/local/html
